# Generated by Django 4.2.4 on 2023-09-09 04:45

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog/posts/default.png', null=True, upload_to=blog.models.post_media_directory),
        ),
    ]
